### ISSUE TITLE
Failed to start the application on windows

### ISSUE THREAD

**Issue by ghost** [anotherangrymouse/cuttlefish#9]
module.js:338
    throw err;
    ^
Error: Cannot find module 'connect-flash'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\development\Litmus\master\experiments\kraken_ex\cuttlefish\index.js:8:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by GrilloPress** [comment]
Hi @Arch88 this old boilerplate is no longer maintained and hasn't been used for over 2 years. So might be tough to get this going on Windows, never mind anything else.

If you are looking for a good node CMS-y type product/admin tool builder or boilerplate then I would strongly suggest [http://keystonejs.com/](http://keystonejs.com/).

If you are looking for something built on Kraken, i never found anything myself either and I moved on regardless.

Sorry myself / @anotherangrymouse wasn't more help
